font_family JetBrains Nerd Mono
font_size 11.0
bold_font auto
italic_font auto
bold_italic_font auto

confirm_os_window_close 0

foreground #E1E4E8
background #00020A
background_opacity 0.5
cursor #7F9EAD

selection_foreground #000000
selection_background #F5FBFF

active_tab_foreground #00020A
active_tab_background #E1E4E8
inactive_tab_foreground #E1E4E8
inactive_tab_background #00020A

active_border_color #E1E4E8
inactive_border_color #00020A
bell_border_color #0E3E51

color0 #000C12
color1 #0E3E51
color2 #154355
color3 #55463E
color4 #476270
color5 #78808B
color6 #7F858F
color7 #CCD0D6
color8 #8F9196
color9 #13536C
color10	#1C5971
color11	#715D52
color12	#5E8295
color13	#A1ABB9
color14	#AAB1BE
color15	#CCD0D6
