daemonize
ignore-empty-password

font=Jetbrains Mono Nerd Font

clock
timestr=%R

image=~/.config/rofi/.wallpaper

indicator
indicator-radius=90
indicator-thickness=8
indicator-y-position=540
indicator-caps-lock

key-hl-color={{color5 | strip}}
bs-hl-color={{color3 | strip}}
caps-lock-key-hl-color={{color6 | strip}}
caps-lock-bs-hl-color={{color3 | strip}}

separator-color=00000000

inside-color={{background | strip}}33
inside-clear-color={{background | strip}}33
inside-caps-lock-color={{background | strip}}33
inside-ver-color={{background | strip}}33
inside-wrong-color={{background | strip}}33

ring-color={{color0 | strip}}
ring-clear-color={{color3 | strip}}
ring-caps-lock-color={{color6 | strip}}
ring-ver-color={{color4 | strip}}
ring-wrong-color={{color1 | strip}}

line-color=00000000
line-clear-color=00000000
line-caps-lock-color=00000000
line-ver-color=00000000
line-wrong-color=00000000

text-color={{foreground | strip}}
text-clear-color={{color3 | strip}}
text-caps-lock-color={{color6 | strip}}
text-ver-color={{color4 | strip}}
text-wrong-color={{color1 | strip}}
