daemonize
ignore-empty-password
font=Jetbrains Mono Nerd Font

font-size=11

indicator-radius=36
indicator-thickness=4

inside-color=#00000000
ring-color=#0E3E51EE
line-color=#00000000
separator-color=#00000000
text-color=#E1E4E8

key-hl-color=#476270CC
bs-hl-color=#55463E

inside-clear-color=#00000000
ring-clear-color=#154355CC
line-clear-color=#00000000
text-clear-color=#E1E4E8

inside-ver-color=#00000000
ring-ver-color=#476270CC
line-ver-color=#00000000
text-ver-color=#E1E4E8

inside-wrong-color=#00000000
ring-wrong-color=#0E3E51EE
line-wrong-color=#00000000
text-wrong-color=#E1E4E8

inside-caps-lock-color=#00000000
ring-caps-lock-color=#715D52CC
line-caps-lock-color=#00000000
text-caps-lock-color=#E1E4E8

caps-lock-key-hl-color=#AAB1BE
caps-lock-bs-hl-color=#55463E
