daemonize
ignore-empty-password

font=Jetbrains Mono Nerd Font

clock
timestr=%R

image=~/.config/rofi/.wallpaper

indicator
indicator-radius=90
indicator-thickness=8
indicator-y-position=540
indicator-caps-lock

key-hl-color=78808B
bs-hl-color=55463E
caps-lock-key-hl-color=7F858F
caps-lock-bs-hl-color=55463E

separator-color=00000000

inside-color=00020A33
inside-clear-color=00020A33
inside-caps-lock-color=00020A33
inside-ver-color=00020A33
inside-wrong-color=00020A33

ring-color=000C12
ring-clear-color=55463E
ring-caps-lock-color=7F858F
ring-ver-color=476270
ring-wrong-color=0E3E51

line-color=00000000
line-clear-color=00000000
line-caps-lock-color=00000000
line-ver-color=00000000
line-wrong-color=00000000

text-color=E1E4E8
text-clear-color=55463E
text-caps-lock-color=7F858F
text-ver-color=476270
text-wrong-color=0E3E51
