# Old Backgrounds
#exec-once=pacwall
#exec-once=swaybg -i Downloads/starforest.png

# Initalize swww
exec-once=awww-daemon
#exec-once=swww img ~/wallpapers/starforest.png

# Initalize Others
exec-once=waybar
exec-once=dunst
exec-once = swayidle -w before-sleep 'sh -c "swaylock -f && sleep 3"'
